export type Track = { title: string; url: string };

export const PLAYLISTS = [
  { id: "spa", name: "ספא", text: "נגינה רגועה בלי מילים, ללובי שקט." },
  { id: "country", name: "קאנטרי", text: "גיטרה, בנג'ו וכינור, בלי שירה." },
  { id: "jazz", name: "ג'אז רך", text: "ג'אז אינסטרומנטלי לרקע." },
  { id: "classical", name: "קלאסי", text: "יצירות קלאסיות בנגינה בלי מילים." },
  { id: "lounge", name: "טרקלין", text: "ג'אז רך, בוסה ומוזיקת רקע לטרקלין." },
] as const;

export type PlaylistId = (typeof PLAYLISTS)[number]["id"];

const tracks: Record<PlaylistId, Track[]> = {
  spa: [
    { title: "A Very Brady Special", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/A%20Very%20Brady%20Special.mp3" },
    { title: "Airport Lounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Airport%20Lounge.mp3" },
    { title: "Airship Serenity", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Airship%20Serenity.mp3" },
    { title: "Almost Bliss", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Almost%20Bliss.mp3" },
    { title: "Almost New", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Almost%20New.mp3" },
    { title: "Almost in F", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Almost%20in%20F.mp3" },
    { title: "Amazing Grace 2011", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Amazing%20Grace%202011.mp3" },
    { title: "Ambiment", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ambiment.mp3" },
    { title: "Ancient Winds", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ancient%20Winds.mp3" },
    { title: "Andreas Theme", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Andreas%20Theme.mp3" },
    { title: "Avec Soin", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Avec%20Soin.mp3" },
    { title: "Beauty Flow", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Beauty%20Flow.mp3" },
    { title: "Blue Paint", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Blue%20Paint.mp3" },
    { title: "BossaBossa", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/BossaBossa.mp3" },
    { title: "Brittle Rille", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brittle%20Rille.mp3" },
    { title: "Canon In D For 8 Bit Synths", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20In%20D%20For%208%20Bit%20Synths.mp3" },
    { title: "Canon In D Interstellar Mix", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20In%20D%20Interstellar%20Mix.mp3" },
    { title: "Canon in D for Autoharp", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20in%20D%20for%20Autoharp.mp3" },
    { title: "Canon in D for Two Harps", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20in%20D%20for%20Two%20Harps.mp3" },
    { title: "Canon in D for Two Renaissance Harps", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20in%20D%20for%20Two%20Renaissance%20Harps.mp3" },
    { title: "Carefree", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carefree.mp3" },
    { title: "Casa Bossa Nova", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Casa%20Bossa%20Nova.mp3" },
    { title: "Cattails", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cattails.mp3" },
    { title: "Cello Suite #1 in G - Prelude", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cello%20Suite%201%20in%20G%20-%20Prelude.mp3" },
    { title: "Cherry Blossom", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cherry%20Blossom.mp3" },
    { title: "Clean Soul", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clean%20Soul.mp3" },
    { title: "Clear Air", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clear%20Air.mp3" },
    { title: "Clear Waters", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clear%20Waters.mp3" },
    { title: "Concentration", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Concentration.mp3" },
    { title: "Continue Life", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Continue%20Life.mp3" },
    { title: "Cool Vibes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cool%20Vibes.mp3" },
    { title: "Cottages", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Magic%20Scout%20-%20Cottages.mp3" },
    { title: "Crinoline Dreams", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Crinoline%20Dreams.mp3" },
    { title: "DD Groove", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/DD%20Groove.mp3" },
    { title: "Daily Beetle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Daily%20Beetle.mp3" },
    { title: "Danse Morialta", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Danse%20Morialta.mp3" },
    { title: "Daybreak", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Daybreak.mp3" },
    { title: "Deep Relaxation", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Deep%20Relaxation.mp3" },
    { title: "Del Rio Bravo", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Del%20Rio%20Bravo.mp3" },
    { title: "Devonshire Waltz Allegretto", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Devonshire%20Waltz%20Allegretto.mp3" },
    { title: "Devonshire Waltz Andante", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Devonshire%20Waltz%20Andante.mp3" },
    { title: "Devonshire Waltz Moderato", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Devonshire%20Waltz%20Moderato.mp3" },
    { title: "Dewdrop Fantasy", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dewdrop%20Fantasy.mp3" },
    { title: "Disquiet", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Disquiet.mp3" },
    { title: "Dream Culture", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dream%20Culture.mp3" },
    { title: "Dreamer", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dreamer.mp3" },
    { title: "Dreams Become Real", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dreams%20Become%20Real.mp3" },
    { title: "Drone in D", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Drone%20in%20D.mp3" },
    { title: "Eastminster", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Eastminster.mp3" },
    { title: "Elf Meditation", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Elf%20Meditation.mp3" },
  ],
  country: [
    { title: "Achaidh Cheide", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Achaidh%20Cheide.mp3" },
    { title: "Anamalie", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Anamalie.mp3" },
    { title: "As I Figure", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/As%20I%20Figure.mp3" },
    { title: "Bama Country", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bama%20Country.mp3" },
    { title: "Carefree", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carefree.mp3" },
    { title: "Carpe Diem", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carpe%20Diem.mp3" },
    { title: "Cattails", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cattails.mp3" },
    { title: "Celtic Impulse", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Celtic%20Impulse.mp3" },
    { title: "Comin Round the Mountain", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Comin%20Round%20the%20Mountain.mp3" },
    { title: "Crossing the Divide", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Crossing%20the%20Divide.mp3" },
    { title: "Daily Beetle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Daily%20Beetle.mp3" },
    { title: "DarxieLand", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/DarxieLand.mp3" },
    { title: "Drankin Song", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Drankin%20Song.mp3" },
    { title: "Duet Musette", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Duet%20Musette.mp3" },
    { title: "Electro Cabello", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Electro%20Cabello.mp3" },
    { title: "Fiddles McGinty", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fiddles%20McGinty.mp3" },
    { title: "Fireflies and Stardust", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fireflies%20and%20Stardust.mp3" },
    { title: "Flying Kerfuffle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Flying%20Kerfuffle.mp3" },
    { title: "Fretless", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fretless.mp3" },
    { title: "Galway", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Galway.mp3" },
    { title: "Glitter Blast", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Glitter%20Blast.mp3" },
    { title: "Guts and Bourbon", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Guts%20and%20Bourbon.mp3" },
    { title: "Happy Alley", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Happy%20Alley.mp3" },
    { title: "Hillbilly Swing", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hillbilly%20Swing.mp3" },
    { title: "Hustle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hustle.mp3" },
    { title: "Hyperfun", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hyperfun.mp3" },
    { title: "Ishikari Lore", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ishikari%20Lore.mp3" },
    { title: "Island Meet and Greet", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Island%20Meet%20and%20Greet.mp3" },
    { title: "Just As Soon", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Just%20As%20Soon.mp3" },
    { title: "Kings of Tara", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Kings%20of%20Tara.mp3" },
    { title: "Leaving Home", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Leaving%20Home.mp3" },
    { title: "Life of Riley", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Life%20of%20Riley.mp3" },
    { title: "Matt's Blues", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Matts%20Blues.mp3" },
    { title: "Meatball Parade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Meatball%20Parade.mp3" },
    { title: "Minstrel Guild", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Minstrel%20Guild.mp3" },
    { title: "Modern Jazz Samba", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Modern%20Jazz%20Samba.mp3" },
    { title: "Nano Hoedown", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Nano%20Hoedown.mp3" },
    { title: "Neo Western", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Neo%20Western.mp3" },
    { title: "Newer Wave", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Newer%20Wave.mp3" },
    { title: "No Frills Cumbia", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/CumbiaNoFrillsFaster.mp3" },
    { title: "Onion Capers", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Onion%20Capers.mp3" },
    { title: "Pale Rider", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pale%20Rider.mp3" },
    { title: "Pennsylvania Rose", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pennsylvania%20Rose.mp3" },
    { title: "Porch Blues", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Porch%20Blues.mp3" },
    { title: "Rainbows", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Rainbows.mp3" },
    { title: "River Valley Breakdown", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/River%20Valley%20Breakdown.mp3" },
    { title: "Robo-Western", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Robo-Western.mp3" },
    { title: "Shenyang", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Shenyang.mp3" },
    { title: "Song of the Volga Boatmen", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Song%20of%20the%20Volga%20Boatmen.mp3" },
    { title: "Still Pickin", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Still%20Pickin.mp3" },
  ],
  jazz: [
    { title: "Acid Trumpet", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/AcidJazz.mp3" },
    { title: "Airport Lounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Airport%20Lounge.mp3" },
    { title: "Apero Hour", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Apero%20Hour.mp3" },
    { title: "As I Figure", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/As%20I%20Figure.mp3" },
    { title: "Awesome Call", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Awesome%20Call.mp3" },
    { title: "Backbay Lounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backbay%20Lounge.mp3" },
    { title: "Backed Vibes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backed%20Vibes.mp3" },
    { title: "Backed Vibes (clean)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backed%20Vibes%20Clean.mp3" },
    { title: "Bass Soli", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bass%20Soli.mp3" },
    { title: "Bass Vibes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bass%20Vibes.mp3" },
    { title: "Bass Walker", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bass%20Walker.mp3" },
    { title: "Bossa Antigua", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bossa%20Antigua.mp3" },
    { title: "Cool Blast", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cool%20Blast.mp3" },
    { title: "Cool Vibes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cool%20Vibes.mp3" },
    { title: "Covert Affair", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Covert%20Affair.mp3" },
    { title: "Crinoline Dreams", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Crinoline%20Dreams.mp3" },
    { title: "Deadly Roulette", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Deadly%20Roulette.mp3" },
    { title: "Deuces", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Deuces.mp3" },
    { title: "Dispersion Relation", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dispersion%20Relation.mp3" },
    { title: "Faster Does It", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Faster%20Does%20It.mp3" },
    { title: "Fuzzball Parade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fuzzball%20Parade.mp3" },
    { title: "George Street Shuffle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/George%20Street%20Shuffle.mp3" },
    { title: "Groove Grove", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Groove%20Grove.mp3" },
    { title: "Hard Boiled", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hard%20Boiled.mp3" },
    { title: "Hep Cats", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hep%20Cats.mp3" },
    { title: "I Knew a Guy", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Knew%20a%20Guy.mp3" },
    { title: "In Your Arms", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/In%20Your%20Arms.mp3" },
    { title: "Intractable", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Intractable.mp3" },
    { title: "Jazz Brunch", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Jazz%20Brunch.mp3" },
    { title: "Just As Soon", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Just%20As%20Soon.mp3" },
    { title: "Kool Kats", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Kool%20Kats.mp3" },
    { title: "Lobby Time", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Lobby%20Time.mp3" },
    { title: "Local Forecast", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast.mp3" },
    { title: "Local Forecast - Elevator", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Elevator.mp3" },
    { title: "Local Forecast - Slower", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Slower.mp3" },
    { title: "Long Stroll", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Long%20Stroll.mp3" },
    { title: "Mining by Moonlight", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Mining%20by%20Moonlight.mp3" },
    { title: "Night in Venice", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Night%20in%20Venice.mp3" },
    { title: "Night on the Docks - Piano", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Night%20on%20the%20Docks.mp3" },
    { title: "Night on the Docks - Sax", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Night%20on%20the%20Docks%20-%20Sax.mp3" },
    { title: "Night on the Docks - Trumpet", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Night%20on%20the%20Docks%20-%20Trumpet.mp3" },
    { title: "No Good Layabout", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/NoGoodLayabout.mp3" },
    { title: "Nouvelle Noel", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Nouvelle%20Noel.mp3" },
    { title: "Off to Osaka", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Off%20to%20Osaka.mp3" },
    { title: "On Hold for You", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20Hold%20for%20You.mp3" },
    { title: "On the Cool Side", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20the%20Cool%20Side.mp3" },
    { title: "On the Ground", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20the%20Ground.mp3" },
    { title: "Opportunity Walks", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Opportunity%20Walks.mp3" },
    { title: "Past Sadness", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Past%20Sadness.mp3" },
    { title: "Poppers and Prosecco", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Poppers%20and%20Prosecco.mp3" },
  ],
  classical: [
    { title: "Amazing Grace 2011", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Amazing%20Grace%202011.mp3" },
    { title: "Aquarium", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Aquarium.mp3" },
    { title: "Blue Feather", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Blue%20Feather.mp3" },
    { title: "Brandenburg Concerto No. 4 in G, Movement I (Allegro), BWV 1049", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brandenburg%20No4-1%20BWV1049.mp3" },
    { title: "Canon In D For 8 Bit Synths", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20In%20D%20For%208%20Bit%20Synths.mp3" },
    { title: "Canon In D Interstellar Mix", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20In%20D%20Interstellar%20Mix.mp3" },
    { title: "Canon in D Major", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20in%20D%20Major.mp3" },
    { title: "Canon in D for Autoharp", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20in%20D%20for%20Autoharp.mp3" },
    { title: "Canon in D for Two Harps", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20in%20D%20for%20Two%20Harps.mp3" },
    { title: "Canon in D for Two Renaissance Harps", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Canon%20in%20D%20for%20Two%20Renaissance%20Harps.mp3" },
    { title: "Cello Suite #1 in G - Prelude", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cello%20Suite%201%20in%20G%20-%20Prelude.mp3" },
    { title: "Chromatic Fantasia (Bach BWV 930)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Chomatic3Fantasia.mp3" },
    { title: "Chromatic Fuge (Bach BWV 930)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Chomatic2Fuge.mp3" },
    { title: "Dance of the Sugar Plum Fairy", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dance%20of%20the%20Sugar%20Plum%20Fairy.mp3" },
    { title: "Danse Macabre", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Danse%20Macabre.mp3" },
    { title: "Divertimento K131", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Divertimento%20K131.mp3" },
    { title: "Divertissement - Pizzicato (from the ballet Sylvia)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Divertissement.mp3" },
    { title: "Egmont Overture", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Egmont%20Overture.mp3" },
    { title: "Egmont Overture Finale", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Egmont%20Overture%20Finale.mp3" },
    { title: "Fox Tale Waltz Part 1", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fox%20Tale%20Waltz%20Part%201.mp3" },
    { title: "Fox Tale Waltz Part 1 Instrumental", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fox%20Tale%20Waltz%20Part%201%20Instrumental.mp3" },
    { title: "Funeral March for Brass", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Funeral%20March%20for%20Brass.mp3" },
    { title: "Ghost Dance", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ghost%20Dance.mp3" },
    { title: "Gymnopedie No. 1", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Gymnopedie%20No%201.mp3" },
    { title: "Gymnopedie No. 2", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Gymnopedie%20No%202.mp3" },
    { title: "Gymnopedie No. 3", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Gymnopedie%20No%203.mp3" },
    { title: "Hall of the Mountain King", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hall%20of%20the%20Mountain%20King.mp3" },
    { title: "Minstrel Guild", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Minstrel%20Guild.mp3" },
    { title: "Mourning Song", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Mourning%20Song.mp3" },
    { title: "Prelude in C (BWV 846)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Prelude%20in%20C%20-%20BWV%20846.mp3" },
    { title: "Ranz des Vaches", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ranz%20des%20Vaches.mp3" },
    { title: "Relent", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Relent.mp3" },
    { title: "Sheep May Safely Graze - BWV 208", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sheep%20May%20Safely%20Graze%20-%20BWV%20208.mp3" },
    { title: "Sinfonia Number 5", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sinfonia%20Number%205.mp3" },
    { title: "Song of the Volga Boatmen", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Song%20of%20the%20Volga%20Boatmen.mp3" },
    { title: "String Impromptu Number 1", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/String%20Impromptu%20Number%201.mp3" },
    { title: "Thaxted (Holst)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Thaxted.mp3" },
    { title: "Toccata and Fugue in D Minor", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Toccata%20and%20Fugue%20in%20D%20Minor.mp3" },
    { title: "Trio for Piano Violin and Viola", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Trio%20for%20Piano%20Violin%20and%20Viola.mp3" },
    { title: "Valse Gymnopedie", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Valse%20Gymnopedie.mp3" },
    { title: "Virtutes Instrumenti", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Virtutes%20Instrumenti.mp3" },
    { title: "Wagner Bridal Chorus", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wagner%20Bridal%20Chorus.mp3" },
    { title: "Wagner Bridal Chorus - piano", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wagner%20Bridal%20Chorus%20-%20piano.mp3" },
    { title: "Waltz (Tschikovsky Op. 40)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Waltz%20-%20Tschikovsky%20Op.%2040.mp3" },
  ],
  lounge: [
    { title: "Lobby Time", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Lobby%20Time.mp3" },
    { title: "Smooth Lovin", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Smooth%20Lovin.mp3" },
    { title: "Easy Lemon", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Easy%20Lemon.mp3" },
    { title: "Bossa Antigua", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bossa%20Antigua.mp3" },
    { title: "George Street Shuffle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/George%20Street%20Shuffle.mp3" },
    { title: "Local Forecast", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast.mp3" },
    { title: "Wallpaper", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wallpaper.mp3" },
    { title: "Backed Vibes Clean", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backed%20Vibes%20Clean.mp3" },
    { title: "Backed Vibes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backed%20Vibes.mp3" },
    { title: "Sidewalk Shade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sidewalk%20Shade.mp3" },
    { title: "Smooth Move", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Smooth%20Move.mp3" },
    { title: "Jazz Brunch", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Jazz%20Brunch.mp3" },
    { title: "On Hold for You", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20Hold%20for%20You.mp3" },
    { title: "Samba Isobel", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Samba%20Isobel.mp3" },
    { title: "Suave Standpipe", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Suave%20Standpipe.mp3" },
    { title: "Take a Chance", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Take%20a%20Chance.mp3" },
    { title: "Two Finger Johnny", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Two%20Finger%20Johnny.mp3" },
    { title: "Walking Along", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Walking%20Along.mp3" },
    { title: "I Knew a Guy", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Knew%20a%20Guy.mp3" },
    { title: "Jarvic 8", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Jarvic%208.mp3" },
    { title: "Latin Industries", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Latin%20Industries.mp3" },
    { title: "Night on the Docks", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Night%20on%20the%20Docks.mp3" },
    { title: "Rollin at 5", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Rollin%20at%205.mp3" },
    { title: "Fuzzball Parade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fuzzball%20Parade.mp3" },
    { title: "Easy Jam", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Easy%20Jam.mp3" },
    { title: "Hot Swing", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hot%20Swing.mp3" },
    { title: "Midnight Tale", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Midnight%20Tale.mp3" },
    { title: "Shades of Spring", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Shades%20of%20Spring.mp3" },
    { title: "Ice Flow", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ice%20Flow.mp3" },
    { title: "Parisian", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Parisian.mp3" },
    { title: "Off to Osaka", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Off%20to%20Osaka.mp3" },
    { title: "Wholesome", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wholesome.mp3" },
    { title: "OctoBlues", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/OctoBlues.mp3" },
    { title: "Backbay Lounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backbay%20Lounge.mp3" },
    { title: "Slow Burn", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Slow%20Burn.mp3" },
    { title: "Local Forecast - Elevator", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Elevator.mp3" },
    { title: "AcidJazz", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/AcidJazz.mp3" },
    { title: "Chill Wave", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Chill%20Wave.mp3" },
    { title: "Late Night Radio", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Late%20Night%20Radio.mp3" },
    { title: "Blue Feather", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Blue%20Feather.mp3" },
    { title: "Evening", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Evening.mp3" },
    { title: "Modern Jazz Samba", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Modern%20Jazz%20Samba.mp3" },
    { title: "Moonlight Hall", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Moonlight%20Hall.mp3" },
    { title: "Night in Venice", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Night%20in%20Venice.mp3" },
    { title: "Radio Martini", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Radio%20Martini.mp3" },
    { title: "Too Cool", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Too%20Cool.mp3" },
    { title: "Vibe Ace", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Vibe%20Ace.mp3" },
    { title: "Five Card Shuffle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Five%20Card%20Shuffle.mp3" },
    { title: "Dances and Dames", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dances%20and%20Dames.mp3" },
    { title: "That Zen Moment", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/That%20Zen%20Moment.mp3" },
    { title: "Water Lily", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Water%20Lily.mp3" },
  ],
};

const PLAYLIST_IDS = new Set<string>(PLAYLISTS.map((playlist) => playlist.id));

export function tracksFor(playlist: string) {
  if (!playlist || playlist === "off") return [];
  const seen = new Set<string>();
  const list: Track[] = [];
  for (const id of playlist.split(",")) {
    const key = id.trim();
    if (!(key in tracks)) continue;
    for (const track of tracks[key as PlaylistId]) {
      if (seen.has(track.url)) continue;
      seen.add(track.url);
      list.push(track);
    }
  }
  return list;
}

export function normalizePlaylists(values: string[]) {
  const ids = [...new Set(values.filter((value) => PLAYLIST_IDS.has(value)))];
  return ids.length ? ids.join(",") : "off";
}
